
---
- name: Build docker image & deploy on docker container
  gather_facts: true
  hosts: localhost
  tasks:
    - name: Build the image on local
      docker_image:
       name: arunbuee/abc-technology
       source: build
       build:
        path: .
       tag: latest
    - name: Log into DockerHub
      docker_login:
       username: nareshdt99
       password: withCredentials([string(credentialsId: 'dockerhub', variable: 'dockerhub')]){ sh 'docker login -u nareshdt99 -p ${dockerhub}}
       email: nareshdt99@gmail.com
    - name: Tag and push to docker hub on local
      docker_image:
       name: nareshdt99/abctechnologies-1.0
       repository: nareshdt99/abctechnologies-1.0
       push: yes
       source: local
    - name: Remove image
      ignore_errors: yes
      docker_image:
       state: absent
       name: nareshdt99/abctechnologies-1.0
       tag: latest
    - name: Log into DockerHub
      docker_login:
       username: nareshdt99
       password: ${dockerhub}
       email: nareshdt99@gmail.com
    - name: Pull image from dockerhub repo
      docker_image:
       name: nareshdt99/abctechnologies-1.0
       source: pull
    - name: Create the container
      docker_container:
       name: abctechnologies
       image: nareshdt99/abctechnologies-1.0:latest
       ports:
        - "80:8070"
    - name: install Pod network
      become: yes
      become_user: jenkins
      shell: kubectl apply -f https://raw.githubusercontent.com/nareshdt99/mainproject/main/kube-deployment.yml
      ignore_errors: true
      args:
        chdir: $HOME
...
