---
- hosts: localhost
  gather_facts: no
  become: yes
  tasks:
    - name: create deployment
      command: kubectl apply -f https://kubernetes-deploy.s3.ap-south-1.amazonaws.com/controller.yml
      
